require('dotenv').config();
const { supabase } = require('../src/config/database');

// Seed the schemes table with real Indian government agriculture schemes.
// Run with:  node scripts/fetchGovtSchemes.js
//
// Table columns: id (auto), name, description, category, state, created_at (auto)

const SCHEMES = [
  {
    name: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
    description: "Direct income support scheme providing Rs.6,000 per year to all landholding farmer families, paid in three equal installments of Rs.2,000 each. Register at pmkisan.gov.in or nearest CSC with Aadhaar and land records. Helpline: 155261.",
    category: "subsidy",
    state: "All India"
  },
  {
    name: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    description: "Comprehensive crop insurance scheme for farmers suffering crop loss due to natural calamities, pests, and diseases. Premium: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops. Apply through bank, CSC, or pmfby.gov.in. Helpline: 1800-200-7710.",
    category: "insurance",
    state: "All India"
  },
  {
    name: "Kisan Credit Card (KCC)",
    description: "Provides affordable short-term credit for cultivation, post-harvest expenses, and consumption needs. Interest rate ~4% p.a. with subvention. Credit limit up to Rs.3 lakh based on land holding. Apply at any commercial, cooperative, or regional rural bank.",
    category: "loan",
    state: "All India"
  },
  {
    name: "Soil Health Card Scheme",
    description: "Free soil testing and personalised Soil Health Card with crop-wise fertiliser recommendations issued every 2 years. Improves yield by 8-10% on average. Cards generated by state agriculture departments. Visit soilhealth.dac.gov.in.",
    category: "other",
    state: "All India"
  },
  {
    name: "Pradhan Mantri Krishi Sinchai Yojana (PMKSY)",
    description: "Ensures access to protective irrigation ('Har Khet Ko Paani') and promotes water-use efficiency through micro/drip irrigation. Subsidy of 55% for small/marginal farmers and 45% for others on drip and sprinkler systems. Apply through state agriculture department.",
    category: "subsidy",
    state: "All India"
  },
  {
    name: "e-NAM (National Agriculture Market)",
    description: "Pan-India electronic trading portal linking APMC mandis for transparent price discovery, online bidding, and direct payment to farmer bank accounts. Register on enam.gov.in with Aadhaar. Helpline: 1800-270-0224.",
    category: "other",
    state: "All India"
  },
  {
    name: "Paramparagat Krishi Vikas Yojana (PKVY)",
    description: "Promotes organic farming through cluster approach with Rs.50,000 per hectare over 3 years for organic inputs, seeds, infrastructure, and certification. Groups of 50+ farmers can apply via state agriculture department.",
    category: "subsidy",
    state: "All India"
  },
  {
    name: "Agriculture Infrastructure Fund (AIF)",
    description: "Medium-to-long term financing for post-harvest management infrastructure. 3% interest subvention on loans up to Rs.2 crore with credit guarantee. Farmers, FPOs, and agri-entrepreneurs can apply at agriinfra.dac.gov.in.",
    category: "loan",
    state: "All India"
  },
  {
    name: "Sub-Mission on Agricultural Mechanization (SMAM)",
    description: "Subsidies of 40-50% on purchase of farm machinery and equipment. Up to 80% for SC/ST/small/marginal/women farmers and NE states. Apply on state DBT Agriculture portal or District Agriculture Office. Visit agrimachinery.nic.in.",
    category: "subsidy",
    state: "All India"
  },
  {
    name: "PM Kisan Maandhan Yojana",
    description: "Voluntary pension scheme for small and marginal farmers (18-40 years, up to 2 hectares). Guaranteed pension of Rs.3,000/month after age 60 with equal govt matching contribution. Register at CSC or maandhan.in. Helpline: 1800-267-6888.",
    category: "other",
    state: "All India"
  }
];

async function seedSchemes() {
  console.log(`Seeding ${SCHEMES.length} government agriculture schemes...`);

  // Clean up any test data first
  await supabase.from('schemes').delete().eq('name', 'ColTest');
  await supabase.from('schemes').delete().eq('name', 'X');

  for (const scheme of SCHEMES) {
    // Check if already exists by name
    const { data: existing } = await supabase
      .from('schemes')
      .select('id')
      .eq('name', scheme.name)
      .limit(1);

    if (existing && existing.length > 0) {
      // Update existing
      const { error } = await supabase
        .from('schemes')
        .update(scheme)
        .eq('id', existing[0].id);

      if (error) {
        console.error(`✗ Failed to update "${scheme.name}":`, error.message);
      } else {
        console.log(`↻ Updated: ${scheme.name}`);
      }
    } else {
      // Insert new
      const { error } = await supabase
        .from('schemes')
        .insert(scheme);

      if (error) {
        console.error(`✗ Failed to insert "${scheme.name}":`, error.message);
      } else {
        console.log(`✓ Inserted: ${scheme.name}`);
      }
    }
  }

  console.log('\nDone! Seeding complete.');
  process.exit(0);
}

seedSchemes();
